name: "Tag PRs with merge conflicts"
on:
  push:
  pull_request_target:
    types: [synchronize]

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: "Check if there's any conflict"
        uses: eps1lon/actions-label-merge-conflict@v3
        with:
          dirtyLabel: "conflicts"
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          commentOnDirty: "This PR has conflicts, resolve them before coding! 😄"
          commentOnClean: "Conflicts were resolved!"
