name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20, 22]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node-version }} version
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Run build
        run: npm run build
