name: PR update

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 20

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Run build
        run: npm run build

      - name: Update all PRs
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          limit: 10
          include_drafts: true
