name: PR update

on:
  push:
    branches:
      - main

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          cache: npm
          node-version: 20

      - name: Install dependencies
        run: npm ci --no-audit --no-fund --no-progress

      - name: Run build
        run: npm run build

      - name: Update all PRs
        uses: ./
        with:
          token: ${{ secrets.PAT_TOKEN }}
          limit: 10
          include_drafts: true
